language: node_js
node_js:
  - 12

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
  
# required super user access
sudo: required

notifications:
  email:
    on_success: always # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - komal.rathore@harbingergroup.com

services:
  - docker

before_install:
  - git config --global user.email "anurathore350@gmail.com"
  - docker build -t webapp -f Dockerfile .

script: "bundle exec rake test:$TEST_SUITE"

after_success:
  - docker build -t webapp .
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker tag webapp 111222333444anu/webapp
  - docker push docker.io/111222333444anu/webapp:latest
