language: node_js
node_js:
  - 12
  
# required super user access
sudo: required


# series of steps ran before the test
before_install:
  - npm install

# triggering travis ci to run this script to have the test
script:
  - npm run build
  - npm run test
