language: node_js
node_js:
  - 12
  
# required super user access
sudo: required

services:
  - docker

before_install:
  - docker build -t webapp -f Dockerfile .

script:
  - docker run -e CI=true webapp npm run test

after_success:
  - docker build -t webapp .
  - echo "Rishudev67890#" | docker login -u "111222333444anu" --password-stdin
  - docker push webapp
 
