language: node_js
node_js:
  - 12
  
# required super user access
sudo: required

services:
  - docker

before_install:
  - docker build -t webapp -f Dockerfile .

# script:
#   - docker run -e CI=true webapp npm run test

after_success:
  - docker build -t webapp .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push webapp
 
